# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pets.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'pets.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npets.proto\x12\x04pets\"\x07\n\x05\x45mpty\".\n\x03Pet\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x62reed\x18\x03 \x01(\t\"#\n\x08PetsList\x12\x17\n\x04pets\x18\x01 \x03(\x0b\x32\t.pets.Pet25\n\nPetService\x12\'\n\x08ListPets\x12\x0b.pets.Empty\x1a\x0e.pets.PetsListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pets_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=20
  _globals['_EMPTY']._serialized_end=27
  _globals['_PET']._serialized_start=29
  _globals['_PET']._serialized_end=75
  _globals['_PETSLIST']._serialized_start=77
  _globals['_PETSLIST']._serialized_end=112
  _globals['_PETSERVICE']._serialized_start=114
  _globals['_PETSERVICE']._serialized_end=167
# @@protoc_insertion_point(module_scope)
